
package interfaz;

import business.Person;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTextField;

public class DisplayJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayJPanel
     */
    //Person person;
    public DisplayJPanel(Person person) {
        initComponents();
       // this.person=person;
        displayPerson(MainJFrame.lista.get(MainJFrame.getContPerfil()));
    }
    
    public void displayPerson(Person person){
        
        nameTextField.setText(person.getName());
        emailTextField.setText(person.getEmail());
        ssnTextField.setText(person.getSsn());
        dobTextField.setText(person.getDob());
        geoTextField.setText(person.getGeographic_data());
        bankTextField.setText(person.getBankAccNum());
        phoneTextField.setText(person.getPhone());
        codTextField.setText(String.valueOf(person.getCodigo()));
        depTextField.setText(String.valueOf(person.getDept()));
        incorporacionTextField.setText(String.valueOf(person.getIncorporate()));
        sueldoTextField.setText(person.getSueldo());
        
        String imageTxt= person.getImagetxt();
       // imagePatTxt.setText(imageTxt);
        
        try {
            BufferedImage img = ImageIO.read(new File(imageTxt));

            imageLabel.setBounds(100, 100, 280, 250);

            Image dimg = img.getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(),
                    Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(dimg);

            imageLabel.setIcon(icon);
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        dobTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bankTextField = new javax.swing.JTextField();
        ssnTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        geoTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        imageLabel.setBackground(new java.awt.Color(102, 102, 102));
        imageLabel.setOpaque(true);

        dobTextField.setEditable(false);

        jLabel2.setText("Name: ");

        jLabel3.setText("Geographic Data: ");

        jLabel4.setText("Date of Birth: ");

        jLabel5.setText("Phone: ");

        jLabel7.setText("Email: ");

        jLabel8.setText("Social Security Number: ");

        jLabel9.setText("Bank Account Number: ");

        bankTextField.setEditable(false);

        ssnTextField.setEditable(false);

        emailTextField.setEditable(false);
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        phoneTextField.setEditable(false);

        geoTextField.setEditable(false);

        nameTextField.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Display Profile");
        
        JLabel lbl11 = new JLabel("Codigo:");
        
        codTextField = new JTextField();
        codTextField.setEditable(false);
        codTextField.setColumns(10);
        
        lblDepartamento = new JLabel("Departamento:");
        
        depTextField = new JTextField();
        depTextField.setEditable(false);
        depTextField.setColumns(10);
        
        lblFechaDeIncorporacion = new JLabel("Fecha de incorporacion:");
        
        incorporacionTextField = new JTextField();
        incorporacionTextField.setEditable(false);
        incorporacionTextField.setColumns(10);
        
        lblSueldo = new JLabel("Sueldo:");
        
        sueldoTextField = new JTextField();
        sueldoTextField.setEditable(false);
        sueldoTextField.setColumns(10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(64)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel8)
        								.addComponent(jLabel9)
        								.addComponent(lbl11)
        								.addComponent(lblDepartamento)
        								.addComponent(lblFechaDeIncorporacion)
        								.addComponent(lblSueldo))
        							.addGap(9, 9, Short.MAX_VALUE)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(sueldoTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addGroup(Alignment.TRAILING, layout.createParallelGroup(Alignment.LEADING)
        									.addComponent(codTextField, 244, 244, 244)
        									.addComponent(bankTextField, 244, 244, 244)
        									.addComponent(ssnTextField, GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
        									.addComponent(depTextField, 244, 244, 244)
        									.addComponent(incorporacionTextField, 244, 244, 244))))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel3)
        							.addPreferredGap(ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
        							.addComponent(geoTextField, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE))
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        								.addComponent(jLabel7, Alignment.LEADING)
        								.addComponent(jLabel5, Alignment.LEADING)
        								.addComponent(jLabel4, Alignment.LEADING))
        							.addGap(0, 326, Short.MAX_VALUE))
        						.addGroup(layout.createSequentialGroup()
        							.addGap(0, 181, Short.MAX_VALUE)
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        								.addComponent(emailTextField, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)
        								.addComponent(phoneTextField, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)
        								.addComponent(dobTextField, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel2)
        							.addPreferredGap(ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
        							.addComponent(nameTextField, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE))))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap(277, Short.MAX_VALUE)
        					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 212, GroupLayout.PREFERRED_SIZE)))
        			.addGap(69)
        			.addComponent(imageLabel, GroupLayout.PREFERRED_SIZE, 274, GroupLayout.PREFERRED_SIZE)
        			.addGap(260))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(74)
        			.addComponent(jLabel1)
        			.addGap(68)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel2)
        							.addGap(18)
        							.addComponent(jLabel3))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(nameTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(geoTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel4)
        						.addComponent(dobTextField, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel5)
        						.addComponent(phoneTextField, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(31)
        							.addComponent(emailTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        						.addGroup(layout.createSequentialGroup()
        							.addGap(32)
        							.addComponent(jLabel7)))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(jLabel8)
        								.addComponent(ssnTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(jLabel9))
        						.addComponent(bankTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(imageLabel, GroupLayout.PREFERRED_SIZE, 238, GroupLayout.PREFERRED_SIZE)
        					.addGap(36)))
        			.addGap(31)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lbl11)
        				.addComponent(codTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblDepartamento)
        				.addComponent(depTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblFechaDeIncorporacion)
        				.addComponent(incorporacionTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblSueldo)
        				.addComponent(sueldoTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(45, Short.MAX_VALUE))
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bankTextField;
    private javax.swing.JTextField dobTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField geoTextField;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JTextField ssnTextField;
    private JTextField codTextField;
    private JLabel lblDepartamento;
    private JTextField depTextField;
    private JLabel lblFechaDeIncorporacion;
    private JTextField incorporacionTextField;
    private JLabel lblSueldo;
    private JTextField sueldoTextField;
}