/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import business.Person;
import business.Person.Departamento;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.awt.event.ActionEvent;

/**
 *
 * @author ankit
 */
public class MainJFrame extends javax.swing.JFrame {
	
	private static int contPerfil=0;
	
	public static int getContPerfil() {
        return contPerfil;
    }

    public static void setContPerfil(int contPerfil) {
        MainJFrame.contPerfil = contPerfil;
    }

    /**
     * Creates new form MainJFrame
     */
    
    Person person;
    public MainJFrame() {
        initComponents();
        person= new Person();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlJPanel = new javax.swing.JPanel();
        createPerson = new javax.swing.JButton();
        viewPerson = new javax.swing.JButton();
        displayJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createPerson.setText("Create Profile");
        createPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPersonActionPerformed(evt);
            }
        });

        viewPerson.setText("Display Profile");
        viewPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPersonActionPerformed(evt);
            }
        });
        
        btnGuardar = new JButton("Guardar");
        btnGuardar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		
        		try {
					FileWriter fw = new FileWriter("login1.txt");
					PrintWriter pw = new PrintWriter(fw);
					
					  for (Person p : MainJFrame.lista) {
					
					pw.println(p.getName());
					pw.println(p.getGeographic_data());
					pw.println(p.getDob());
					pw.println(p.getPhone());
					pw.println(p.getEmail());
					pw.println(p.getSsn());
					pw.println(p.getImagetxt());
					pw.println(p.getBankAccNum());					
					pw.println(p.getCodigo());
					pw.println(p.getDept());
					pw.println(p.getIncorporate());
					pw.println(p.getSueldo());
					
					  }
					
					pw.close();
					
					
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
        		
        	}
        });
        
        btnCargar = new JButton("Cargar");
        btnCargar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		
        		try {
					FileReader fr = new FileReader("login1.txt");
					BufferedReader br = new BufferedReader(fr);
					Scanner s=new Scanner(br);
					
					 while (s.hasNextLine()) {
			                // Leer los datos de una nueva persona del archivo
			                String name = s.nextLine();
			                String geographicData = s.nextLine();
			                String dob = s.nextLine();
			                String phone = s.nextLine();
			                String email = s.nextLine();
			                String ssn = s.nextLine();
			                String imageTxt = s.nextLine();
			                String bankAccNum = s.nextLine();			               
			                int codigo = Integer.parseInt(s.nextLine());
			                Departamento dept = Departamento.valueOf(s.nextLine());
			                String incorporate = s.nextLine();
			                String sueldo = s.nextLine();
			                
			                
			                
			                // Crear una nueva instancia de Person y agregarla a la lista
			                MainJFrame.lista.add(new Person(name, geographicData, dob, phone, email, ssn, imageTxt, bankAccNum, dept, incorporate, codigo, sueldo));
			            }
			            
			            br.close();
					
					/*
					MainJFrame.lista.get(MainJFrame.contador).setName(s.nextLine());
					MainJFrame.lista.get(MainJFrame.contador).setDob(s.nextLine());
					MainJFrame.lista.get(MainJFrame.contador).setBankAccNum(s.nextLine());
					MainJFrame.lista.get(MainJFrame.contador).setEmail(s.nextLine());
					MainJFrame.lista.get(MainJFrame.contador).setSsn(s.nextLine());
					MainJFrame.lista.get(MainJFrame.contador).setPhone(s.nextLine());
					MainJFrame.lista.get(MainJFrame.contador).setGeographic_data(s.nextLine());
					MainJFrame.lista.get(MainJFrame.contador).setCodigo(Integer.parseInt(s.nextLine()));
					MainJFrame.lista.get(MainJFrame.contador).setIncorporate(s.nextLine());
					MainJFrame.lista.get(MainJFrame.contador).setDept(Departamento.valueOf(s.nextLine()));
					MainJFrame.lista.get(MainJFrame.contador).setImageTxt(s.nextLine());
					*/
					
				} catch (FileNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
        		
        		
        	}
        });
        
        btnSiguiente = new JButton("Siguiente");
        btnSiguiente.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		
        		
        		if(MainJFrame.getContPerfil() == lista.size()-1) {
        			
        			 JOptionPane.showMessageDialog(null, "No hay mas perfiles");
        		} else {
        		MainJFrame.setContPerfil(MainJFrame.getContPerfil()+1);
        		viewPerson.doClick();
        		}
        		
        		//if(MainJFrame.getContPerfil() < lista.size()) {
        		//DisplayJPanel viewJPanel = new DisplayJPanel(MainJFrame.lista.get(MainJFrame.getContPerfil()));
        		//jSplitPanel.setRightComponent(viewJPanel);
        		//}
        		
        	}
        });
        
        btnAnterior = new JButton("Anterior");
        btnAnterior.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	
        		
        		
        		if(MainJFrame.getContPerfil() == 0) {
        			
        			 JOptionPane.showMessageDialog(null, "No hay mas perfiles");
        		} else {
        			
        		MainJFrame.setContPerfil(MainJFrame.getContPerfil()-1);
        		
        		viewPerson.doClick();
        		
        		}
        	}
        });
       

        javax.swing.GroupLayout controlJPanelLayout = new javax.swing.GroupLayout(controlJPanel);
        controlJPanelLayout.setHorizontalGroup(
        	controlJPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(controlJPanelLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(controlJPanelLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(viewPerson)
        				.addComponent(createPerson)
        				.addComponent(btnGuardar, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnCargar, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnSiguiente)
        				.addComponent(btnAnterior))
        			.addContainerGap(100, Short.MAX_VALUE))
        );
        controlJPanelLayout.setVerticalGroup(
        	controlJPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(controlJPanelLayout.createSequentialGroup()
        			.addGap(123)
        			.addComponent(createPerson)
        			.addGap(144)
        			.addComponent(viewPerson)
        			.addGap(18)
        			.addComponent(btnGuardar)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(btnCargar)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(btnSiguiente)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(btnAnterior)
        			.addContainerGap(13, Short.MAX_VALUE))
        );
        controlJPanel.setLayout(controlJPanelLayout);

        jSplitPane1.setLeftComponent(controlJPanel);

        javax.swing.GroupLayout displayJPanelLayout = new javax.swing.GroupLayout(displayJPanel);
        displayJPanel.setLayout(displayJPanelLayout);
        displayJPanelLayout.setHorizontalGroup(
            displayJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );
        displayJPanelLayout.setVerticalGroup(
            displayJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(displayJPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPersonActionPerformed
        // TODO add your handling code here:
        CreateJPanel createJPanel= new CreateJPanel(person);
        jSplitPane1.setRightComponent(createJPanel);
        
        
    }//GEN-LAST:event_createPersonActionPerformed

    private void viewPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPersonActionPerformed
        // TODO add your handling code here:
        
        DisplayJPanel viewJPanel= new DisplayJPanel(person);
        jSplitPane1.setRightComponent(viewJPanel);
        
        
    }//GEN-LAST:event_viewPersonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    	
    	
    	
   
    	
    	
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlJPanel;
    private javax.swing.JButton createPerson;
    private javax.swing.JPanel displayJPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton viewPerson;
    public JButton btnGuardar;
    public JButton btnCargar;
    private JButton btnSiguiente;
    private JButton btnAnterior;
    
    public static List<Person> lista=new ArrayList<>();
    
}